# syntax=docker/dockerfile:1
FROM alpine:edge
RUN apk add --no-cach tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apk del tzdata
