# syntax=docker/dockerfile:1
FROM golang:alpine AS builder
ARG version=2.2.5
RUN apk add --no-cache git make && \
    wget https://github.com/m13253/dns-over-https/archive/v${version}.tar.gz && \
    tar zxf v${version}.tar.gz && \
    mv ./dns-over-https-${version} /src && \
    cd /src && \
    make doh-client/doh-client

FROM playn/alpine
COPY --from=builder /src/doh-client/doh-client /doh-client

EXPOSE 53
EXPOSE 5380

ENTRYPOINT ["/doh-client"]
CMD ["-conf", "/doh-client.conf"]