# syntax=docker/dockerfile:1
FROM golang:alpine AS builder
WORKDIR /go/src
ENV CGO_ENABLED=0
RUN apk --no-cache add git && \
    git clone https://github.com/crossfw/Air-Universe.git && cd cmd/Air-Universe && \
    go mod download && \
    go env -w GOFLAGS=-buildvcs=false && \
    go build -v -o au -trimpath -ldflags "-s -w -buildid="

FROM playn/alpine
COPY --from=builder /go/src/Air-Universe/cmd/Air-Universe/au /usr/local/bin

ENTRYPOINT [ "au", "-c", "/etc/au/config.json"]