# syntax=docker/dockerfile:1
FROM playn/alpine
# ARG version=0.37.0
RUN export version=$(wget -qO- https://api.github.com/repos/fatedier/frp/releases/latest | grep '"tag_name":' | head -n 1 | sed -E 's/.*"([^"]+)".*/\1/') && \
    wget -c https://github.com/fatedier/frp/releases/download/v${version}/frp_${version}_linux_amd64.tar.gz && \
    tar zxf frp_${version}_linux_amd64.tar.gz -C /tmp && \
    mv /tmp/frp_${version}_linux_amd64/frps /usr/local/bin && \
    rm -rf frp_${version}_linux_amd64.tar.gz /tmp/* && \
    unset version
ENTRYPOINT [ "/usr/local/bin/frps" ]