# syntax=docker/dockerfile:1
FROM playn/alpine
ARG version=0.37.0
RUN wget https://github.com/fatedier/frp/releases/download/v${version}/frp_${version}_linux_amd64.tar.gz && \
    tar zxf frp_${version}_linux_amd64.tar.gz -C /tmp && \
    mv /tmp/frp_${version}_linux_amd64/frps /usr/local/bin && \
    rm -rf frp_${version}_linux_amd64.tar.gz /tmp/*
ENTRYPOINT [ "/usr/local/bin/frps" ]