# syntax=docker/dockerfile:1
FROM playn/alpine
# ARG version=20210624
RUN export version=$(wget -qO- https://api.github.com/repos/xtaci/kcptun/releases/latest | grep '"tag_name":' | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/v//g;s/,//g;s/ //g') && \
    wget --quiet -O /tmp/kcptun.tar.gz https://github.com/xtaci/kcptun/releases/download/v${version}/kcptun-linux-amd64-${version}.tar.gz && \
    tar zxf /tmp/kcptun.tar.gz -C /tmp && \
    mv /tmp/client_linux_amd64 /usr/local/bin/kcptun_client && \
    rm -rf /tmp/* && \
    unset version
ENTRYPOINT ["/usr/local/bin/kcptun_client"]