# syntax=docker/dockerfile:1
FROM playn/alpine
# ARG version=20210624
RUN export version=$(wget -qO- https://api.github.com/repos/xtaci/kcptun/releases/latest | grep '"tag_name":' | head -n 1 | sed -E 's/.*"([^"]+)".*/\1/') && \
    wget -c https://github.com/xtaci/kcptun/releases/download/v${version}/kcptun-linux-amd64-${version}.tar.gz && \
    tar zxf kcptun-linux-amd64-${version}.tar.gz -C /tmp && \
    mv /tmp/client_linux_amd64 /usr/local/bin/kcptun_client && \
    rm -rf kcptun-linux-amd64-${version}.tar.gz /tmp/* && \
    unset version
ENTRYPOINT ["/usr/local/bin/kcptun_client"]