# syntax=docker/dockerfile:1
FROM playn/alpine
ARG version=20210624
RUN wget https://github.com/xtaci/kcptun/releases/download/v${version}/kcptun-linux-amd64-${version}.tar.gz && \
    tar zxf kcptun-linux-amd64-${version}.tar.gz -C /tmp && \
    mv /tmp/client_linux_amd64 /usr/bin/kcptun_client && \
    rm -rf kcptun-linux-amd64-${version}.tar.gz /tmp/*
ENTRYPOINT ["/usr/bin/kcptun_client"]