name: Build NaïveProxy

on:
  push:
  # branches: [ master ]
    paths:
      - 'naiveproxy/**'
      - '.github/workflows/build-naiveproxy.yml'
  # UTC +8
  schedule:
    - cron: "0 20 7 * *"
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:

jobs:
  build-naiveproxy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          echo "NAIVE_VERSION=$(curl -fsSL https://api.github.com/repos/klzgrad/naiveproxy/releases/latest | grep '"tag_name":' | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/v//g;s/,//g;s/ //g')" >> $GITHUB_ENV
        shell: bash

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        id: docker_build_naiveproxy
        with:
          context: ./naive
          file: ./naive/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/naive:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/naive:${{ env.NAIVE_VERSION }}
          builder: ${{ steps.buildx.outputs.name }}

      - name: Image digest
        run: |
          echo ${{ steps.docker_build_naiveproxy.outputs.digest }}
