name: Build ENCRYPTED DNS

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

  workflow_dispatch:

jobs:
  build-encrypted-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          echo "EDNS_VERSION=$(curl -fsSL https://api.github.com/repos/DNSCrypt/encrypted-dns-server/tags | grep '"name":' | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/v//g;s/,//g;s/ //g')" >> $GITHUB_ENV
        shell: bash

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build encrypted-dns and push
        uses: docker/build-push-action@v5
        id: docker_build_encrypted_dns
        with:
          context: ./encrypted-dns
          file: ./encrypted-dns/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/encrypted-dns:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/encrypted-dns:${{ env.EDNS_VERSION }}
          builder: ${{ steps.buildx.outputs.name }}

      - name: Image digest
        run: |
          echo ${{ steps.docker_build_encrypted_dns.outputs.digest }}
