name: Build LEGO(go-acme)

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

  workflow_dispatch:

jobs:
  build-lego:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          echo "LEGO_VERSION=$(curl -fsSL https://api.github.com/repos/go-acme/lego/releases/latest | grep '"tag_name":' | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/v//g;s/,//g;s/ //g')" >> $GITHUB_ENV
        shell: bash

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build lego and push
        uses: docker/build-push-action@v3
        id: docker_build_lego
        with:
          context: ./lego
          file: ./lego/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/lego:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/lego:${{ env.LEGO_VERSION }}
          builder: ${{ steps.buildx.outputs.name }}

      - name: Image digest
        run: |
          echo ${{ steps.docker_build_lego.outputs.digest }}