name: Build ENCRYPTED DNS

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

  workflow_dispatch:

jobs:
  build-doh-server:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build doh-server and push
        id: docker_build_doh_server
        uses: docker/build-push-action@v2
        with:
          context: ./doh-server
          file: ./doh-server/Dockerfile.server
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/doh-server:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/doh-server:2.3.1
          builder: ${{ steps.buildx.outputs.name }}

      - name: Image digest
        run: |
          echo ${{ steps.docker_build_doh_server.outputs.digest }}
