name: Build Frp

on:
  workflow_dispatch:

jobs:
  build-frp:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          echo "FRP_VERSION=$(curl -fsSL https://api.github.com/repos/fatedier/frp/releases/latest | grep '"tag_name":' | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/v//g;s/,//g;s/ //g')" >> $GITHUB_ENV
        shell: bash

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frps and push
        uses: docker/build-push-action@v5
        id: docker_build_frps
        with:
          context: ./frp
          file: ./frp/Dockerfile.server
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/frp:server
            ${{ secrets.DOCKER_HUB_USERNAME }}/frp:${{ env.FRP_VERSION }}-server
            ghcr.io/${{ github.repository }}/frp:server
            ghcr.io/${{ github.repository }}/frp:${{ env.FRP_VERSION }}-server
          builder: ${{ steps.buildx.outputs.name }}

      - name: Build frpc and push
        uses: docker/build-push-action@v5
        id: docker_build_frpc
        with:
          context: ./frp
          file: ./frp/Dockerfile.client
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/frp:client
            ${{ secrets.DOCKER_HUB_USERNAME }}/frp:${{ env.FRP_VERSION }}-client
            ghcr.io/${{ github.repository }}/frp:client
            ghcr.io/${{ github.repository }}/frp:${{ env.FRP_VERSION }}-client
          builder: ${{ steps.buildx.outputs.name }}

      - name: Image digest
        run: |
          echo ${{ steps.docker_build_frps.outputs.digest }}
          echo ${{ steps.docker_build_frpc.outputs.digest }}
