name: Build sing-box

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "选择构建类型"
        required: true
        default: "stable"
        type: choice
        options:
          - stable
          - pre-release
  release:
    types: [published]
    repositories: [SagerNet/sing-box]

jobs:
  build-sing-box:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      # 自动触发时获取 release 版本号
      - name: Get Release Version (Auto Trigger)
        if: github.event_name == 'release'
        run: |
          echo "SINGBOX_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "BUILD_TYPE=stable" >> $GITHUB_ENV

      # 手动触发时获取最新版本号
      - name: Get Latest Version (Manual Trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ inputs.build_type }}" == "stable" ]; then
            VERSION=$(curl -fsSL https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep '"tag_name":' | head -n 1 | awk -F '"' '{print $4}' | sed 's/v//')
            echo "BUILD_TYPE=stable" >> $GITHUB_ENV
          else
            VERSION=$(curl -fsSL https://api.github.com/repos/SagerNet/sing-box/tags | grep '"name":' | head -n 1 | awk -F '"' '{print $4}' | sed 's/v//')
            echo "BUILD_TYPE=pre-release" >> $GITHUB_ENV
          fi
          echo "SINGBOX_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 稳定版构建
      - name: Build Stable Image
        if: env.BUILD_TYPE == 'stable'
        run: |
          docker build -f ./sing-box/Dockerfile.latest -t ${{ secrets.DOCKER_HUB_USERNAME }}/sing-box:latest ./sing-box
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/sing-box:latest ${{ secrets.DOCKER_HUB_USERNAME }}/sing-box:${{ env.SINGBOX_VERSION }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sing-box:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sing-box:${{ env.SINGBOX_VERSION }}

          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/sing-box:latest ghcr.io/${{ github.repository }}/sing-box:latest
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/sing-box:latest ghcr.io/${{ github.repository }}/sing-box:${{ env.SINGBOX_VERSION }}
          docker push ghcr.io/${{ github.repository }}/sing-box:latest
          docker push ghcr.io/${{ github.repository }}/sing-box:${{ env.SINGBOX_VERSION }}

      # Pre-release 构建
      - name: Build Pre-release Image
        if: env.BUILD_TYPE == 'pre-release'
        run: |
          docker build -f ./sing-box/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/sing-box:${{ env.SINGBOX_VERSION }} ./sing-box
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sing-box:${{ env.SINGBOX_VERSION }}

          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/sing-box:${{ env.SINGBOX_VERSION }} ghcr.io/${{ github.repository }}/sing-box:${{ env.SINGBOX_VERSION }}
          docker push ghcr.io/${{ github.repository }}/sing-box:${{ env.SINGBOX_VERSION }}
