name: Build DNS Over HTTPS

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

  workflow_dispatch:

jobs:
  build-doh-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          echo "DOH_VERSION=$(curl -fsSL https://api.github.com/repos/m13253/dns-over-https/tags | grep '"name":' | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/v//g;s/,//g;s/ //g')" >> $GITHUB_ENV
        shell: bash

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build doh-server and push
        uses: docker/build-push-action@v3
        id: docker_build_doh_server
        with:
          context: ./doh-server
          file: ./doh-server/Dockerfile.server
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/doh-server:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/doh-server:${{ env.DOH_VERSION }}
          builder: ${{ steps.buildx.outputs.name }}

      - name: Image digest
        run: |
          echo ${{ steps.docker_build_doh_server.outputs.digest }}
