name: Build AdGuardHome

on:
  workflow_dispatch:
  release:
    types: [published]
    repositories: [AdguardTeam/AdGuardHome]

jobs:
  build-adguardhome:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          echo "ADGUARDHOME_VERSION=$(curl -fsSL https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest | grep '"tag_name":' | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/v//g;s/,//g;s/ //g')" >> $GITHUB_ENV
        shell: bash

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ./adguardhome
          file: ./adguardhome/Dockerfile.latest
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/adguardhome:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/adguardhome:${{ env.ADGUARDHOME_VERSION }}
            ghcr.io/${{ github.repository }}/adguardhome:latest
            ghcr.io/${{ github.repository }}/adguardhome:${{ env.ADGUARDHOME_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
