name: Build Caddy

on:
  workflow_dispatch:
  release:
    types: [published]
    repositories: [caddyserver/caddy]

jobs:
  build-caddy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          echo "CADDY_VERSION=$(curl -fsSL https://api.github.com/repos/caddyserver/caddy/releases/latest | grep '\"tag_name\":' | head -n 1 | awk -F ':' '{print $2}' | tr -d ',"' | tr -d '[:space:]' | sed 's/v//')" >> $GITHUB_ENV
        shell: bash

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./caddy/v2
          file: ./caddy/v2/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/caddy:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/caddy:${{ env.CADDY_VERSION }}
            ghcr.io/${{ github.repository }}/caddy:latest
            ghcr.io/${{ github.repository }}/caddy:${{ env.CADDY_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
