name: Build LEGO(go-acme)

on:
  workflow_dispatch:
  release:
    types: [published]
    repositories: [go-acme/lego]

jobs:
  build-lego:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          echo "LEGO_VERSION=$(curl -fsSL https://api.github.com/repos/go-acme/lego/releases/latest | grep '"tag_name":' | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/v//g;s/,//g;s/ //g')" >> $GITHUB_ENV
        shell: bash

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build lego and push
        uses: docker/build-push-action@v5
        with:
          context: ./lego
          file: ./lego/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/lego:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/lego:${{ env.LEGO_VERSION }}
            ghcr.io/${{ github.repository }}/lego:latest
            ghcr.io/${{ github.repository }}/lego:${{ env.LEGO_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
