name: Build Traefik

on:
  # push:
  #   branches: [ master ]
  #   paths:
  #     - 'traefik/**'
  #     - '.github/workflows/build-traefik.yml'
  # pull_request:
  #   branches: [ master ]
  # UTC +8
  schedule:
    - cron: "0 20 */14 * *"
  workflow_dispatch:

jobs:
  build-traefik:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          echo "TRAEFIK_PRE_VERSION=$(curl -fsSL https://api.github.com/repos/traefik/traefik/tags | grep '"name":' | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/v//g;s/,//g;s/ //g')" >> $GITHUB_ENV
          echo "TRAEFIK_VERSION=$(curl -fsSL https://api.github.com/repos/traefik/traefik/releases/latest | grep '"tag_name":' | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/v//g;s/,//g;s/ //g')" >> $GITHUB_ENV
        shell: bash

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        id: docker_build_traefik
        with:
          context: ./traefik
          file: ./traefik/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/traefik:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/traefik:${{ env.TRAEFIK_VERSION }}
          builder: ${{ steps.buildx.outputs.name }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        id: docker_build_traefik_pre
        with:
          context: ./traefik
          file: ./traefik/Dockerfile.pre
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/traefik:${{ env.TRAEFIK_PRE_VERSION }}
          builder: ${{ steps.buildx.outputs.name }}

      - name: Image digest
        run: |
          echo ${{ steps.docker_build_traefik.outputs.digest }}
          echo ${{ steps.docker_build_traefik_pre.outputs.digest }}
