name: Build ENCRYPTED DNS

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

  workflow_dispatch:

jobs:
  build-encrypted-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build encrypted-dns and push
        id: docker_build_encrypted_dns
        uses: docker/build-push-action@v2
        with:
          context: ./encrypted-dns
          file: ./encrypted-dns/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/encrypted-dns:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/encrypted-dns:0.9.1
          builder: ${{ steps.buildx.outputs.name }}

      - name: Image digest
        run: |
          echo ${{ steps.docker_build_encrypted_dns.outputs.digest }}
