name: Build DNSCrypt-Proxy

on:
  # UTC +8 [https://crontab.guru/]
  schedule:
    - cron: "0 20 15,30 * *"
  workflow_dispatch:

jobs:
  build-dnscrypt-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          echo "DNSCRYPT_PROXY_VERSION=$(curl -fsSL https://api.github.com/repos/dnscrypt/dnscrypt-proxy/releases/latest | grep '"tag_name":' | head -n 1 | sed -E 's/.*"([^"]+)".*/\1/')" >> $GITHUB_ENV
        shell: bash

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build DNSCrypt-Proxy and push
        uses: docker/build-push-action@v3
        id: docker_build_dnscrypt_proxy
        with:
          context: ./dnscrypt-proxy
          file: ./dnscrypt-proxy/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/dnscrypt-proxy:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/dnscrypt-proxy:${{ env.DNSCRYPT_PROXY_VERSION }}
          builder: ${{ steps.buildx.outputs.name }}

      - name: Image digest
        run: |
          echo ${{ steps.docker_build_dnscrypt_proxy.outputs.digest }}
