# This is a basic workflow to help you get started with Actions
name: CI to Docker Hub

on:
  push:
    # branches: [ master ]
    # paths:
    #   - '**/**'
    #   - '.github/workflows/main.yml'
    paths-ignore:
      - "**/**"
  # pull_request:
  #   branches: [ master ]
  # UTC +8 https://tool.lu/crontab/
  schedule:
    - cron: "0 22 */29 * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-basic:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        id: docker_build_apline_latest
        with:
          context: ./alpine
          file: ./alpine/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/alpine:latest
          builder: ${{ steps.buildx.outputs.name }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        id: docker_build_apline_edge
        with:
          context: ./alpine
          file: ./alpine/Dockerfile.edge
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/alpine:edge
          builder: ${{ steps.buildx.outputs.name }}

      - name: Image digest
        run: |
          echo ${{ steps.docker_build_apline_latest.outputs.digest }}
          echo ${{ steps.docker_build_apline_edge.outputs.digest }}
