name: Monitor Releases

on:
  schedule:
    - cron: '0 0 * * *' # 每天零点执行
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Check Latest Release
        id: check_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/sagernet/sing-box/releases/latest | jq -r '.tag_name')
          echo "Latest release is $latest_release"
          echo "::set-output name=latest_release::$latest_release"
        shell: bash
          
      - name: Send Notification if New Release
        if: steps.check_release.outputs.latest_release != github.ref
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.qq.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: New Release Available for sagernet/sing-box
          body: |
            A new release is available for sagernet/sing-box.
            Latest release: ${{ steps.check_release.outputs.latest_release }}
            Repository: ${{ github.repository }}
          to: ${{ secrets.EMAIL }}
