name: Monitor Releases

on:
  schedule:
    - cron: "0 0 * * *" # 每天零点执行
  workflow_dispatch: # 手动触发

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Latest Release
        id: check_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/sagernet/sing-box/releases/latest | jq -r '.tag_name')
          echo "Latest release is $latest_release"
          echo "latest_release=$latest_release" >> $GITHUB_ENV
        shell: bash

      - name: Send Notification if New Release
        if: ${{ env.latest_release }} != ${{ github.ref }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: New Release Available for sagernet/sing-box
          body: |
            A new release is available for sagernet/sing-box.
            Latest release: ${{ env.latest_release }}
            Repository: ${{ github.repository }}
          to: ${{ secrets.EMAIL }}
