name: Renew Certificate

on:
  schedule:
    - cron: "0 23 */1 */1 *" # every day 23:00
    # - cron: "0 23 20 */2 *" # every 2 months 20 23:00
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Renew Certificate
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HKG_HOSTNAME }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          # fingerprint: ${{ secrets.VPS_FINGERPRINT }}
          script_stop: true
          script: |
            cd /root/devops/docker/common/base/lego
            bash docker_run.sh
