name: Renew Certificate

on:
  schedule:
    - cron: "0 23 11 */1 *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Renew Certificate
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.VPS_HOSTNAME }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          # fingerprint: ${{ secrets.VPS_FINGERPRINT }}
          # script_stop: true
          script: |
            cd ~/devops/docker/common/base/lego
            bash docker_run.sh
