# syntax=docker/dockerfile:1
FROM playn/alpine AS builder
RUN apk update --no-cache && \
    apk add --no-cache rust cargo make && \
    cargo install doh-proxy

FROM playn/alpine
COPY --from=builder /root/.cargo/bin/doh-proxy /usr/local/bin/doh-proxy
RUN apk add --no-cache libgcc
ENTRYPOINT [ "/usr/local/bin/doh-proxy" ]